### ISSUE TITLE
Two features

### ISSUE THREAD

**Issue by resouer** [ZJU-SEL/kube-in-docker#1]
- [x] Merge into one shell (as master and minion differ very little)
- [x] Support both ubuntu & centos (apt-get, /etc/default/docker)

**Comment by WIZARD-CXY** [comment]
make sense

**Comment by WIZARD-CXY** [comment]
feature #2 complished!
feature #1 Mr chang said it's just ok

**Comment by resouer** [comment]
As Mr chang said that, I'll close this issue, keep a eye on how to set flannel subnet configurable,.

**Comment by WIZARD-CXY** [comment]
GOT IT
