### ISSUE TITLE
open flannel.tar : no such file or directory

### ISSUE THREAD

**Issue by sli4** [ZJU-SEL/kube-in-docker#10]
when i try to deploy kubernetes according to the "kube-in-docker" docs, I met the problem, which says "open flannel.tar : no such file or directory", And I don't know how to solve it, please help me, thanks

**Comment by resouer** [comment]
@sli4 kube-in-docker is now for our internal usage, so it may not meet your local env. And of course we have commit all of this to upstream, so please move to use https://github.com/kubernetes/kube-deploy/tree/master/docker-multinode.
