### ISSUE TITLE
Should deprecate NamespaceExists admission controller plugin

### ISSUE THREAD

**Issue by dalanlan** [ZJU-SEL/kube-in-docker#7]
Use `NamespaceExists` instead of `NamespaceAutoProvision`.
Do figure out a way to create a new namespace.

See also [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/admission-controllers.md#namespaceautoprovision-deprecated).

**Comment by dalanlan** [comment]
Not specified the corresponding parameter here. Just keep this for k8s/cluster/ubuntu. <api-sever>

**Comment by dalanlan** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/10495

**Comment by dalanlan** [comment]
Or temporarily use a yaml file as [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/namespace.yaml).

**Comment by WIZARD-CXY** [comment]
LGTM
