### ISSUE TITLE
How does it manage containers ?

### ISSUE THREAD

**Issue by mavencode01** [ZJU-SEL/kube-in-docker#9]
Is this going to pull containers inside the container ?

**Comment by dalanlan** [comment]
Where did you catch that, if i may ask?

**Comment by mavencode01** [comment]
@dalanlan maybe I'm making an assumptions here, but this is scritps allows you to run Kubernetes in Docker.
So your master runs inside a docker and your minions will run inside a docker ?
Kubernetes is suppose to manage containers on the host when you install it on the host but if it runs inside a docker, how is it suppose to manage (pull, restart, etc.) the docker containers on the host ?
since the isolation level of containers cannot allow it to modify the host filesystems

**Comment by dalanlan** [comment]
IIUC, your main concern is about how kubelet manages to sync pods. 
Yet i cannot see why it matters whether it starts as a container or not, while the workflow is to send a http request to docker daemon at the end.

**Comment by mavencode01** [comment]
@dalanlan you are absolutely right!

Thank you

**Comment by dalanlan** [comment]
The enclosed scripts could be quite confused since it's our-env-exclusive.
Certainly you can turn to [here](https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides/docker-multinode) for more details, if it might interest you.
